### ISSUE TITLE
Option - requires an argument.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shekyan/slowhttptest#18]
```
What steps will reproduce the problem?
After installation just enter "slowhttptest -u https://www.google.at or 
anything of the Wiki tutorials. 

What is the expected output? What do you see instead?
root@xfs:~# slowhttptest -u https://www.google.at
Option - requires an argument.
Try 'slowhttptest -h' for more information


What version of the product are you using? On what operating system?
newest version. clean Xubuntu




```

Original issue reported on code.google.com by `insidiou...@gmail.com` on 26 Nov 2013 at 2:36

**Comment by da13m** [comment]
I have a similar issue running on Nexus 9 Nethunter 3.0. Using the latest version of slowhttptest and cut and paste command in terminal any command but -h results in the Option - requires an argument

**Comment by da13m** [comment]
Was there a fix posted for it?

**Comment by shekyan** [comment]
have you tried putting arguments inside double-quotes? Like `slowhttptest "-u www.google.at"`

**Comment by da13m** [comment]
Yes tried a few combinations of syntax but no go but the strange part is only -h works

root@kali:~# slowhttptest "-u www.google.at"
Option - requires an argument.
Try 'slowhttptest -h' for more information

 root@kali:~# slowhttptest -h

slowhttptest, a tool to test for slow HTTP DoS vulnerabilities - version 1.6

**Comment by shekyan** [comment]
Can you please give me the exact environment where this is happening, will try to reproduce

**Comment by da13m** [comment]
Thanks Shekyan,
I'm running Nethunter on a Nexus 9 let me know if this is what your looking for (1.6 version for slowhttptest)

Android version 6.0.1
Kernel version 3.10.40-g6857980-dirty
Build MMB29V
root@kali:~# cat /etc/lsb-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=2.0
DISTRIB_CODENAME=sana
DISTRIB_DESCRIPTION="Kali GNU/Linux 2.0"

**Comment by albinowax** [comment]
This issue is still present in the package supplied by Raspbian. Building the tool from source works fine, though.
