### ISSUE TITLE
Slow HTTP and Slow Post not working as slowloris or rudy

### ISSUE THREAD

**Issue by abdulvehhab** [shekyan/slowhttptest#30]
Hi,

I am installed slowhttptest, 

In link:
https://blog.qualys.com/securitylabs/2011/08/25/new-open-source-tool-for-slow-http-attack-vulnerabilities

says slowloris has lost of generated headers, each of headers has time delay before post.

I am watching your script via netcat server, your code only send standart headers not generated headers.

And also slowpost mode only send foo=bar not generated lots of post

Thanks

**Comment by shekyan** [comment]
I am not sure how are you using netcat. Run slowhttptest with -v 4 to see requests that are going out. Note that slowHTTPTest is first firing a probe connection which is repeated every 5 seconds or whatever is specified in `-p` argument.
