### ISSUE TITLE
OpenSSL-devel missing.

### ISSUE THREAD

**Issue by mdhz** [shekyan/slowhttptest#38]
I am using Kali-rolling.
Even though I've installed libssl-dev, I'm unable to compile it.
Please help out.

Thank you.

**Comment by shekyan** [comment]
do you mind pasting the log ?

**Comment by mdhz** [comment]
root@kali:~/Downloads/slowhttptest-1.7# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for SSL_library_init in -lssl... no
configure: error: OpenSSL-devel is missing

**Comment by shekyan** [comment]
what package manager does it have?
`sudo apt-get install libssl-dev`?
`apt-get install slowhttptest` should be available as well.

**Comment by mdhz** [comment]
Yeah sudo apt-get install libssl-dev is installed.
Will try direct package installation.

**Comment by mdhz** [comment]
FIXED with apt-get install slowhttptest.

**Comment by yizhimanpadewoniu** [comment]
“apt-get install slowhttptest“ is available。good。

**Comment by qfan** [comment]
It's likely because the checking script is using the `SSL_library_init` function to test the existence of the library, but openssl 1.1 [no longer has this init function](https://wiki.openssl.org/index.php/Library_Initialization) and some Linux distributions use 1.1 or above as default installation.

Perhaps try `libssl1.0-dev`?
