### ISSUE TITLE
does not compile on macOS Sierra

### ISSUE THREAD

**Issue by bbaassssiiee** [shekyan/slowhttptest#39]
warning: couldn't understand kern.osversion '16.4.0'

**Comment by shekyan** [comment]
Can you please get latest master and check if warning exists.
If yes, which stage of the build is complaining?

**Comment by shekyan** [comment]
Searching for that warning message hints that running `xcode-select --install` should help aligning tooling with kernel version.

**Comment by bbaassssiiee** [comment]
xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..   -I/usr/local/opt/openssl/include  -g -O2 -MT slowhttptestmain.o -MD -MP -MF .deps/slowhttptestmain.Tpo -c -o slowhttptestmain.o slowhttptestmain.cc
g++: warning: couldn't understand kern.osversion '16.4.0
mv -f .deps/slowhttptestmain.Tpo .deps/slowhttptestmain.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..   -I/usr/local/opt/openssl/include  -g -O2 -MT slowhttptest.o -MD -MP -MF .deps/slowhttptest.Tpo -c -o slowhttptest.o slowhttptest.cc
g++: warning: couldn't understand kern.osversion '16.4.0
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:36:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:36:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:312:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:312:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:6808:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:6808:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:6913:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:6913:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:6918:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:6918:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:7181:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:7181:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:7186:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:7186:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:7241:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:7241:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:7250:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:7250:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:7419:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccQLJ7pI.s:7419:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
mv -f .deps/slowhttptest.Tpo .deps/slowhttptest.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..   -I/usr/local/opt/openssl/include  -g -O2 -MT slowsocket.o -MD -MP -MF .deps/slowsocket.Tpo -c -o slowsocket.o slowsocket.cc
g++: warning: couldn't understand kern.osversion '16.4.0
mv -f .deps/slowsocket.Tpo .deps/slowsocket.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..   -I/usr/local/opt/openssl/include  -g -O2 -MT slowstats.o -MD -MP -MF .deps/slowstats.Tpo -c -o slowstats.o slowstats.cc
g++: warning: couldn't understand kern.osversion '16.4.0
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:6:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:6:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:12:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:12:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:23:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:23:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:79:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:79:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:112:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:112:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:441:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:441:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:549:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:549:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:552:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:552:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:557:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:557:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:750:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:750:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:753:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:753:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:758:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:758:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:875:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:875:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:878:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:878:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:883:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:883:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:1085:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:1085:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:1088:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:1088:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:1358:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:1358:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:1466:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:1466:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:1469:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc5xnwM8.s:1469:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
mv -f .deps/slowstats.Tpo .deps/slowstats.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..   -I/usr/local/opt/openssl/include  -g -O2 -MT slowurl.o -MD -MP -MF .deps/slowurl.Tpo -c -o slowurl.o slowurl.cc
g++: warning: couldn't understand kern.osversion '16.4.0
mv -f .deps/slowurl.Tpo .deps/slowurl.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..   -I/usr/local/opt/openssl/include  -g -O2 -MT slowlog.o -MD -MP -MF .deps/slowlog.Tpo -c -o slowlog.o slowlog.cc
g++: warning: couldn't understand kern.osversion '16.4.0
mv -f .deps/slowlog.Tpo .deps/slowlog.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..   -I/usr/local/opt/openssl/include  -g -O2 -MT text-generator.o -MD -MP -MF .deps/text-generator.Tpo -c -o text-generator.o text-generator.cc
g++: warning: couldn't understand kern.osversion '16.4.0
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccOdZ3PX.s:6:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccOdZ3PX.s:6:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccOdZ3PX.s:12:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccOdZ3PX.s:12:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccOdZ3PX.s:23:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccOdZ3PX.s:23:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccOdZ3PX.s:28:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccOdZ3PX.s:28:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccOdZ3PX.s:44:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//ccOdZ3PX.s:44:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
mv -f .deps/text-generator.Tpo .deps/text-generator.Po
g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..   -I/usr/local/opt/openssl/include  -g -O2 -MT range-generator.o -MD -MP -MF .deps/range-generator.Tpo -c -o range-generator.o range-generator.cc
g++: warning: couldn't understand kern.osversion '16.4.0
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc1JtHSH.s:73:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc1JtHSH.s:73:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc1JtHSH.s:242:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/hs/b03p_c310l70v6zx1byb4l0r0000gp/T//cc1JtHSH.s:242:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
mv -f .deps/range-generator.Tpo .deps/range-generator.Po
g++ -std=c++11  -g -O2  -L/usr/local/opt/openssl/lib -L/usr/local/lib -lssl -o slowhttptest slowhttptestmain.o slowhttptest.o slowsocket.o slowstats.o slowurl.o slowlog.o text-generator.o range-generator.o  -lssl 
g++: warning: couldn't understand kern.osversion '16.4.0
ld: warning: object file (slowhttptestmain.o) was built for newer OSX version (10.12) than being linked (10.4)
ld: warning: object file (slowhttptest.o) was built for newer OSX version (10.12) than being linked (10.4)
ld: warning: object file (slowsocket.o) was built for newer OSX version (10.12) than being linked (10.4)
ld: warning: could not create compact unwind for slowhttptest::SlowHTTPTest::run_test(): stack subq instruction is too different from dwarf stack size
ld: warning: object file (slowstats.o) was built for newer OSX version (10.12) than being linked (10.4)
ld: warning: object file (slowurl.o) was built for newer OSX version (10.12) than being linked (10.4)
ld: warning: object file (slowlog.o) was built for newer OSX version (10.12) than being linked (10.4)
ld: warning: object file (text-generator.o) was built for newer OSX version (10.12) than being linked (10.4)
ld: warning: object file (range-generator.o) was built for newer OSX version (10.12) than being linked (10.4)
Making all in man
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all-am'.

**Comment by LiYaHX** [comment]
[OSX & XCode 8: Endless stream of warnings when compiling](https://github.com/nest/nest-simulator/issues/486)——this article may be help for you
