### ISSUE TITLE
Unable to use it on ipv6

### ISSUE THREAD

**Issue by vinod272** [shekyan/slowhttptest#41]
`slowhttptest -c 1000 -H -i 10 -r 200 -t GET -u https://[fe80::ed21:aac3:20fd:b57e%eth0]/ -x 24 -p 3 -l 200`
is producing the following error:
```
Thu Mar 30 15:47:44 2017:Error in getaddrinfo: Name or service not known
Thu Mar 30 15:47:44 2017:main: error setting up slow HTTP test
```
I dont have any issue using curl to browse to the target at all . #20

**Comment by shekyan** [comment]
I cannot really reproduce because host seems to be down.
Error in slowhttptest I get is `cannot connect socket 3: No route to host`, error in curl is `Failed to connect to fe80::ed21:aac3:20fd:b57e port 443: Host is down`

**Comment by vinod272** [comment]
As its a link local adress it tould be unavailable for you, please check with any other ipv6 link local adress in your LAN.

**Comment by shekyan** [comment]
Fixed the bug. Not sure if interface part should be removed from literal IPv6 in `Host` header as I don't know anything about IPv6.. Feel free to report an issue if that's a problem.
