### ISSUE TITLE
'openssl/ssl.h' file not found during make

### ISSUE THREAD

**Issue by lyenliang** [shekyan/slowhttptest#44]
I get the following error while executing `make` when installing slowhttptest:

    g++ -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT slowhttptest.o -MD -MP -MF .deps/slowhttptest.Tpo -c -o slowhttptest.o slowhttptest.cc
    In file included from slowhttptest.cc:48:
    ./slowsocket.h:36:10: fatal error: 'openssl/ssl.h' file not found
    #include <openssl/ssl.h>

I have openssl installed on my mac

    brew list | grep openssl
    openssl
    openssl@1.1

Anyone knows how to solve this issue?

**Comment by shekyan** [comment]
Have you looked at https://github.com/shekyan/slowhttptest/wiki/InstallationAndUsage? Namely, 
> You need libssl-dev to be installed to successfully compile the tool. Most systems would have it. On OS X, run brew install openssl && brew link openssl --force, if g++ fails to locate ssl.h, run xcode-select --install.

**Comment by lyenliang** [comment]
Oh, sorry, I was in a hurry and didn't read the installation guide thoroughly.
