### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Janevski** [shekyan/slowhttptest#45]
apt-get install slowhttptest -y

While trying the copy pasted examples from the readme:
Option - requires an argument.
Try 'slowhttptest -h' for more information

It never works. It doesn't care that everything is in accordance with the manual.

**Comment by shekyan** [comment]
what is your linux? 
Something simple like `slowhttptest -u http://whatever` works?

**Comment by Janevski** [comment]
<pre>
# apt-get install slowhttptest -y
# slowhttptest -u http://km.mk
Option - requires an argument.
Try 'slowhttptest -h' for more information
# uname -a
Linux x 4.1.6-249 #1 SMP Mon Aug 31 12:34:47 UTC 2015 armv7l GNU/Linux
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.2 (jessie)
Release:	8.2
Codename:	jessie
</pre>

**Comment by shekyan** [comment]
Try to https://github.com/shekyan/slowhttptest/issues/18#ref-commit-af5dbb5

**Comment by shekyan** [comment]
I have no control how people distribute it over apt-get. Somewhere it is using wrong `getopt`

**Comment by Janevski** [comment]
Seems to work on amd64 debian-8.8.0. Something is wrong on the arm systems.

I'll compile it and see what happens.
