### ISSUE TITLE
How to configure slowhttptest to replay this slow read attack

### ISSUE THREAD

**Issue by rokka** [shekyan/slowhttptest#50]
Hi,

I am running a website on an apache webserver which sits behind a nginx proxy.

Scince a couple of days I am faced with attacks like this:

![image](https://user-images.githubusercontent.com/533290/34907971-1ddb1f8c-f888-11e7-863c-b178e63abe14.png)

Looks to me like a slow read attack.

In order to mitigate this attack I am trying to reproduce it in a test environment.

But I can´t figure out which parameters to use to get exactly the same kind of attack where the column "SS (Seconds since beginning of most recent request)" in Apaches Server Status is adding up.

Can you give me a hint how can I achieve this?

greetings
Andre

**Comment by shekyan** [comment]
Hi, 

if I understand you correctly, that should be achieved by specifying relatively large  interval between read operations from recv buffer (-n ) . What do you see with Apache Status when run slow read with default settings?

**Comment by rokka** [comment]
Hi,

the default as mentioned in the wiki:

./slowhttptest -c 1000 -X -r 1000 -w 10 -y 20 -n 5 -z 32 -u "https://xxx" -p 5 -l 350

![image](https://user-images.githubusercontent.com/533290/34909638-39e1a7ba-f8a5-11e7-8afc-2894c57413bc.png)

With "-n 500" still no high SS numbers.


greetings
Andre

**Comment by shekyan** [comment]
Are you attacking from the same machine? If so, try the attack to come through actual network interface instead of loopback, because in case of loopback, as far as I remember things are going throw unix domain sockets and I am not sure if receive window size is even honored.

**Comment by shekyan** [comment]
Although, with default settings for slow read I was able to get high `SS` numbers on default apache on  that comes with MacOS:

<img width="476" alt="screen shot 2018-01-14 at 10 29 43 pm" src="https://user-images.githubusercontent.com/1631049/34929785-b24442e6-f97a-11e7-9918-dffe06a10d4b.png">

**Comment by rokka** [comment]
>Are you attacking from the same machine?
No

>Although, with default settings for slow read I was able to get high SS numbers on default apache on that comes with MacOS
Can you send me your parameters?

I am using an apache behind a nginx proxy. Maybe this is the reason we get different results.


Thanks a lot for your help,
Andre
