### ISSUE TITLE
How to use for Window 8?

### ISSUE THREAD

**Issue by Jackxwb** [shekyan/slowhttptest#51]
I  download the releases file(slowhttptest-1.7.zip) in my disk,but i don't know how to use?(my system is window 8)

**Comment by shekyan** [comment]
You would need to install (Cygwin)[https://www.cygwin.com/], then build as described in https://github.com/shekyan/slowhttptest/wiki/InstallationAndUsage. But, if I were you, I would go (Docker)[https://docs.docker.com/toolbox/toolbox_install_windows/] path.
